### ISSUE TITLE
thanks for not just commiting .dws files

### ISSUE THREAD

**Issue by justin2004** [abrudz/dyalog_vision#1]
it seems like Dyalog APLers like to pass around binary workspace files (oh i'm sure there is some great reason for this) but it is more friendly to newcomers to see the source files.
thanks for doing that.

**Comment by abrudz** [comment]
Binary workspaces contain what is essentially memory dumps, making them the fastest to save and load. Furthermore, they can contain an execution state, so execution can continue when they are loaded. All this makes them great for distributing end-user applications, saving an application state, and providing debugging information. You're absolutely right that they are not good as source code, although a lot of APL code exists only in workspaces for historical reasons.

Dyalog is strongly pushing the plain text files as the modern way to store sources, to enable 3rd party tools, including version control software, and to make inspection of code a breeze. You'll be hard pressed to find any new project of ours that uses workspaces. Even when we do distribute workspaces (for backwards compatibility), we are gradually moving towards building those from text sources.
